branch-defaults:
  default:
    environment: udagramapi-dev
    group_suffix: null
  master:
    environment: Udagramapi-env
deploy:
  artifact: www/Archive.zip
environment-defaults:
  udagramapi-dev:
    branch: null
    repository: udagram
global:
  application_name: udagram-api
  branch: master
  default_ec2_keyname: vockey
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: udagram
  sc: git
  workspace_type: Application
